import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.js</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>
//
//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//         </div>
//
//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>
//
//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>
//
//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>
//
//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }
export default function Home() {
  const workers = [
    {
      name: "Liza Ivanivna",
      experience: 3,
      desc: "my name liza i have 16 yers experiens belive me? i will help you!",
      photo:
        "https://images.pexels.com/photos/2328141/pexels-photo-2328141.jpeg?cs=srgb&dl=pexels-lucas-pezeta-2328141.jpg&fm=jpg",
      link: "https://t.me/NetHunter228",
    },
    {
      name: "Liza Ivanivna",
      experience: 3,
      desc: "my name liza i have 16 yers experiens belive me? i will help you!",
      photo:
        "https://images.pexels.com/photos/2328141/pexels-photo-2328141.jpeg?cs=srgb&dl=pexels-lucas-pezeta-2328141.jpg&fm=jpg",
      link: "https://t.me/NetHunter228",
    },
    {
      name: "Liza Ivanivna",
      experience: 3,
      desc: "my name liza i have 16 yers experiens belive me? i will help you!",
      photo:
        "https://images.pexels.com/photos/2328141/pexels-photo-2328141.jpeg?cs=srgb&dl=pexels-lucas-pezeta-2328141.jpg&fm=jpg",
      link: "https://t.me/NetHunter228",
    },
    {
      name: "Liza Ivanivna",
      experience: 3,
      desc: "my name liza i have 16 yers experiens belive me? i will help you!",
      photo:
        "https://images.pexels.com/photos/2328141/pexels-photo-2328141.jpeg?cs=srgb&dl=pexels-lucas-pezeta-2328141.jpg&fm=jpg",
      link: "https://t.me/NetHunter228",
    },
    {
      name: "Liza Ivanivna",
      experience: 3,
      desc: "my name liza i have 16 yers experiens belive me? i will help you!",
      photo:
        "https://images.pexels.com/photos/2328141/pexels-photo-2328141.jpeg?cs=srgb&dl=pexels-lucas-pezeta-2328141.jpg&fm=jpg",
      link: "https://t.me/NetHunter228",
    },
    {
      name: "Liza Ivanivna",
      experience: 3,
      desc: "my name liza i have 16 yers experiens belive me? i will help you!",
      photo:
        "https://images.pexels.com/photos/2328141/pexels-photo-2328141.jpeg?cs=srgb&dl=pexels-lucas-pezeta-2328141.jpg&fm=jpg",
      link: "https://t.me/NetHunter228",
    },
  ];
  return (
    <>
      <Head>
        <title>Taro Helper</title>
        <meta name="description" content="service for help tarolog" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="main-wrap">
        <div className="container">
          <h1 className={"title"}>Виберіть власного таролога:</h1>
          <ul className="workers-wrap">
            {workers.map((worker) => {
              return (
                <a href={worker.link || "#"}>
                  <div className={"card"}>
                    <img
                      className={"worker-photo"}
                      src={`${worker.photo}`}
                      alt="photo"
                    />
                    <div className="info">
                      <h3 className="name">
                        {worker.name} <span>Exp:{worker.experience}</span>
                      </h3>
                      <p className="desc">{worker.desc}</p>
                    </div>
                  </div>
                </a>
              );
            })}
          </ul>
        </div>
      </main>
    </>
  );
}
